"""Portfolio Post-Processor Module

This module defines the `PortfolioPostProcessor` class, responsible for
performing two main post-parsing operations:

1. Data Cleaning:
   - Reads intermediate `.cleaned` Excel files generated by individual parsers.
   - Standardizes numerical fields and scaling factors based on AMC configuration.
   - Filters invalid or redundant rows.
   - Outputs cleaned results into `.final_cleaned`.

2. Final Compilation:
   - Combines all `.final_cleaned` files.
   - Applies fuzzy mapping of investment categories to standardized labels.
   - Drops unnecessary columns and normalizes column order.
   - Exports a consolidated CSV file for downstream analytics.

The class is designed to be run after all AMC parsers complete execution.
"""

import os
import re
import yaml
import logging
import pandas as pd
import numpy as np
from fuzzywuzzy import process

# Configuration & Constants
logger = logging.getLogger(__name__)

CATEGORY_MAPPING = {
            # Equity & Equity Related
            'EQUITY & EQUITY RELATED': 'Equity & Equity Related',
            'Equity & Equity Related': 'Equity & Equity Related',
            'Equity & Equity related': 'Equity & Equity Related',
            'Equity & Equity Related Instruments': 'Equity & Equity Related',
            'Equity & Equity related Aerospace & Defense': 'Equity & Equity Related',
            'Equity & Equity related Automobiles': 'Equity & Equity Related',
            'Equity & Equity related Banks': 'Equity & Equity Related',
            'Equity & Equity related Biotechnology': 'Equity & Equity Related',
            'Equity & Equity related Capital Markets': 'Equity & Equity Related',
            'Equity & Equity related Construction': 'Equity & Equity Related',
            'Equity & Equity related Consumer Durables': 'Equity & Equity Related',
            'Equity & Equity related Electrical Equipment': 'Equity & Equity Related',
            'Equity & Equity related Exchange Traded Funds': 'Equity & Equity Related',
            'Equity & Equity related Finance': 'Equity & Equity Related',
            'Equity & Equity related IT - Software': 'Equity & Equity Related',
            'Equity & Equity related Industrial Products': 'Equity & Equity Related',
            'Equity & Equity related Pharmaceuticals & Biotechnology': 'Equity & Equity Related',
            'Equity & Equity related Realty': 'Equity & Equity Related',
            'Equity & Equity related Semiconductors': 'Equity & Equity Related',
            'Equity Shares': 'Equity & Equity Related',
            'Equity shares': 'Equity & Equity Related',
            'FOREIGNEQUITYSECURITIES': 'Equity & Equity Related',
            'Foreign Securities - Equity': 'Equity & Equity Related',
            'EQUITYEQUITYRELATED': 'Equity & Equity Related',

            # Exchange Traded Funds (ETFs)
            'Exchange Traded Fund': 'Exchange Traded Funds (ETFs)',
            'Exchange Traded Funds': 'Exchange Traded Funds (ETFs)',
            'EXCHANGE TRADED FUND UNITS': 'Exchange Traded Funds (ETFs)',
            'ETF': 'Exchange Traded Funds (ETFs)',
            'International Exchange Traded Funds': 'Exchange Traded Funds (ETFs)',
            'International Exchange Traded Funds Exchange Traded Funds': 'Exchange Traded Funds (ETFs)',
            'Foreign Securities and/or overseas ETF': 'Exchange Traded Funds (ETFs)',
            'Foreign Securities/Overseas ETFs': 'Exchange Traded Funds (ETFs)',
            'FOREIGNETF': 'Exchange Traded Funds (ETFs)',

            # Bonds & Debentures
            'Corporate Debt Market Development Fund Class': 'Bonds & Debentures',
            'BOND & NCDs': 'Bonds & Debentures',
            'Bonds': 'Bonds & Debentures',
            'Debentures and Bonds': 'Bonds & Debentures',
            'Zero Coupon Bond': 'Bonds & Debentures',
            'Zero Coupon Bonds': 'Bonds & Debentures',
            'Zero Coupon Bonds / Deep Discount Bonds': 'Bonds & Debentures',
            'Non Convertible Debentures': 'Bonds & Debentures',
            'Non Convertible Debentures / Bonds': 'Bonds & Debentures',
            'NON-CONVERTIBLE DEBENTURES/BONDS/ZCB': 'Bonds & Debentures',
            'II NON-CONVERTIBLE DEBENTURES/BONDS': 'Bonds & Debentures',
            'II NON-CONVERTIBLE DEBENTURES/BONDS/ZCB': 'Bonds & Debentures',
            'Convertible Debenture': 'Bonds & Debentures',
            'Compulsory Convertible Debenture': 'Bonds & Debentures',
            'COMPULSORILYCONVERTIBLEDEBENTURE': 'Bonds & Debentures',
            'Fixed rates bonds - Corporate': 'Bonds & Debentures',
            'Debt Instruments': 'Bonds & Debentures',
            'Debt Instruments SOVEREIGN': 'Bonds & Debentures',
            'DEBT INSTRUMENTS': 'Bonds & Debentures',
            'DEBTINSTRUMENTS': 'Bonds & Debentures',
            'Government Bonds': 'Bonds & Debentures',
            'Government Securities': 'Bonds & Debentures',
            'Government Securities / SDL': 'Bonds & Debentures',
            'Government Securities Central/State': 'Bonds & Debentures',
            'Government Securities Central/State Cash & Equivalent': 'Bonds & Debentures',
            'State Government Securities': 'Bonds & Debentures',
            'Govt Security': 'Bonds & Debentures',
            'Govt Securities / SDL': 'Bonds & Debentures',
            'Central Government Securities': 'Bonds & Debentures',
            'GOVERNMENT SECURITIES': 'Bonds & Debentures',
            'GOVERNMENTSECURITIES': 'Bonds & Debentures',
            'GOVERNMENTSECURITIESCENTRALSTATE': 'Bonds & Debentures',
            'i Government Securities': 'Bonds & Debentures',
            'ii State Government Securities': 'Bonds & Debentures',

            # Money Market Instruments
            'Certificate of Deposit': 'Money Market Instruments',
            'Certificate of Deposits': 'Money Market Instruments',
            'Certificate of Deposit IND A': 'Money Market Instruments',
            'Certificate of Deposits C': 'Money Market Instruments',
            'CERTIFICATEOFDEPOSIT': 'Money Market Instruments',
            'CERTIFICATEOFDEPOSITCD': 'Money Market Instruments',
            'CD-Certificate of Deposits': 'Money Market Instruments',
            'Commercial Paper': 'Money Market Instruments',
            'Commercial Papers': 'Money Market Instruments',
            'Commercial Papers C': 'Money Market Instruments',
            'COMMERCIALPAPER': 'Money Market Instruments',
            'COMMERCIALPAPERSCP': 'Money Market Instruments',
            'Treasury Bill': 'Money Market Instruments',
            'Treasury Bills': 'Money Market Instruments',
            'Treasury Bill/Cash Management Bill': 'Money Market Instruments',
            'Treasury Bill/Cash Management Bill CRISIL A': 'Money Market Instruments',
            'Treasury Bill/Cash Management Bill SOVEREIGN': 'Money Market Instruments',
            'TREASURYBILL': 'Money Market Instruments',
            'TREASURYBILLS': 'Money Market Instruments',
            'T-Bil': 'Money Market Instruments',
            'Tri Party Repo TREPs': 'Money Market Instruments',
            'TREPS / Reverse Repo': 'Money Market Instruments',
            'Reverse Repo / TREPS': 'Money Market Instruments',
            'Reverse Repo --': 'Money Market Instruments',

            # Alternative Investments
            'Alternative Investment Fund': 'Alternative Investments',
            'Alternative Investment Fund Units': 'Alternative Investments',
            'Alternative Investment Funds': 'Alternative Investments',
            'Alternative Investment Funds AIF': 'Alternative Investments',
            'Units of an Alternative Investment Fund AIF': 'Alternative Investments',
            'Investment in AIF': 'Alternative Investments',
            'AIF CAT': 'Alternative Investments',
            'ALTERNATIVEINVESTMENTFUND': 'Alternative Investments',
            'ALTERNATIVEINVESTMENTFUNDUNITS': 'Alternative Investments',
            'CDMDFAIF': 'Alternative Investments',
            'Infrastructure Investment Trusts': 'Alternative Investments',
            'Units of Infrastructure Investment Trusts InvITs': 'Alternative Investments',
            'InvIT': 'Alternative Investments',
            'Invits': 'Alternative Investments',
            'Units issued by REITs & InvITs': 'Alternative Investments',
            'REIT': 'Alternative Investments',
            'Reits': 'Alternative Investments',
            'ReIT': 'Alternative Investments',
            'Units of Real Estate Investment Trust REITs': 'Alternative Investments',
            'Real Estate Investment Trusts': 'Alternative Investments',
            'Real Estate Investment Trust': 'Alternative Investments',
            'UNITS OF INVIT': 'Alternative Investments',
            'UNITS OF REIT': 'Alternative Investments',
            'UNITSISSUEDBYINVIT': 'Alternative Investments',
            'UNITSISSUEDBYREIT': 'Alternative Investments',
            'BUNITSOFREALESTATEINVESTMENTTRUSTSREITS': 'Alternative Investments',

            # Other/Uncategorized
            'Others': 'Other/Uncategorized',
            'OTHERS': 'Other/Uncategorized',
            'UNLISTED': 'Other/Uncategorized',
            'Unlisted': 'Other/Uncategorized',
            'Privately Placed / Unlisted': 'Other/Uncategorized',
            'Privately Placed/Unlisted': 'Other/Uncategorized',
            'Privately placed / Unlisted': 'Other/Uncategorized',
            'Option wise per unit Net Asset Values are as follows': 'Other/Uncategorized',
            'ISINCODE securityname Yield to Call': 'Other/Uncategorized',
            'Arbitrage': 'Other/Uncategorized',
            'Numero Uno International Ltd Finance e-': 'Other/Uncategorized',
            'Margin Mutual Fund Units': 'Other/Uncategorized',
            'RISKLEVELBASEDONPORTFOLIOASONMAY': 'Other/Uncategorized',
            'RISKLEVELOFTIERBENCHMARKASONMAY': 'Other/Uncategorized',
            'CMSI': 'Other/Uncategorized',
            'CNX NIFTY-JUN - - -': 'Other/Uncategorized',
            'Amount Rs in Lakhs to NAV': 'Other/Uncategorized',
            'uncategorised': 'Other/Uncategorized'
        }

NOISE_WORDS = [
    "direct", "regular", "growth", "dividend", "div", "option", "plan", 
    "payout", "reinvestment", "bonus", "cumulative", "institutional", 
    "retail", "segregated", "portfolio", "idcw", "series",
    "and", "quarterly", "monthly", "weekly", "daily", "annual"
]

# Class Definition
class PortfolioPostProcessor:
    """
    Unified class combining data cleaning, standardization, and enrichment steps.
    """

    def __init__(self, config_path="./config/amc_configs.yaml"):
        with open(config_path, "r") as f:
            self.configs = yaml.safe_load(f)
        
        default_config = self.configs.get("Defaults", {})
        self.path_bse_schemedata = default_config.get(
            "path_BSE_SchemeData", r"reference\SchemeData0111251523SS.csv"
        )

        if not os.path.exists(self.path_bse_schemedata):
            logger.error(f"Invalid BSE Scheme Data Path: {self.path_bse_schemedata}")
            print(f"Invalid Path BSE Scheme Data Table: {self.path_bse_schemedata}")
            exit(1)
        
        self.output_folder = ".cleaned"
        self.final_folder = ".final_cleaned"
        os.makedirs(self.output_folder, exist_ok=True)
        os.makedirs(self.final_folder, exist_ok=True)
        logger.info("Initialized PortfolioPostProcessor.")

    # Helper Methods
    @staticmethod
    def _clean_numeric_string(s):
        """Convert dirty strings (e.g. '12.5%') to float."""
        s = re.sub("%", "", str(s))
        try:
            return float(s)
        except ValueError:
            # Fallback to regex extraction
            if match := re.findall(r"-?\d+\.\d+", str(s)):
                return float(match[0])
            if match := re.findall(r"-?\d+", str(s)):
                return float(match[0])
            return 0.0

    @staticmethod
    def _standardize_scheme_name(scheme_name):
        """Normalize scheme names for matching by removing noise words."""
        name = str(scheme_name).lower()
        name = re.sub(r"\(.*?\)", "", name)  # Remove content in brackets
        
        # Remove noise words (whole words only)
        pattern = r'\b(?:{})\b'.format('|'.join(NOISE_WORDS))
        name = re.sub(pattern, "", name)
        
        # Remove specific prefixes/suffixes
        for phrase in ["- an.*", "-an.*", "as on.*", "scheme having.*"]:
            name = re.sub(phrase, "", name)

        # Clean special chars and spacing
        name = re.sub(r"[^a-z0-9]", " ", name)
        return re.sub(r"\s+", " ", name).strip()

    @staticmethod
    def _fuzzy_map_category(entries, keys):
        """Map list of entries to standardized categories using fuzzy matching."""
        results = {}
        for entry in entries:
            if not keys:
                results[entry] = "others"
                continue
            
            entry_str = entry.decode("utf-8", errors="ignore") if isinstance(entry, bytes) else str(entry)
            match, _ = process.extractOne(entry_str, keys)
            results[entry] = CATEGORY_MAPPING.get(match, "others")
        return results

    # Core Operations
    def clean_data(self):
        """Read intermediate files, normalize numbers, apply scaling, and save."""
        files = [f for f in os.listdir(self.output_folder) if "~" not in f]
        logger.info(f"Starting data cleaning for {len(files)} files.")

        numeric_cols = [
            "coupon", "quantity", "market value (mkt) ( rs lakh )",
            "% to net assets (nav)", "yield", "yield to call (ytc)"
        ]

        for filename in files:
            file_path = os.path.join(self.output_folder, filename)
            df = pd.read_excel(file_path)
            amc_name = df["AMC"].unique()[0]
            config = self.configs.get(amc_name, {})
            
            logger.info(f"Cleaning data for AMC: {amc_name}")

            # Scaling factors
            scale_100 = [s.lower() for s in config.get("Scale100", [])]
            scale_100th = [s.lower() for s in config.get("Scale100th", [])]

            # Process numeric columns
            for col in numeric_cols:
                if col in df.columns:
                    df[col] = df[col].map(self._clean_numeric_string).astype(np.float64)
                    if col in scale_100th: df[col] /= 100
                    if col in scale_100:   df[col] *= 100
                    df[col] = df[col].fillna(0)

            # Standardize Text Columns
            df["isin"] = df["isin"].apply(lambda x: str(x)[:12])
            
            # Apply specific column logic
            if "% to net assets (nav)" in df.columns:
                df["% to net assets (nav)"] *= 100
            for y_col in ["yield", "yield to call (ytc)"]:
                if y_col in df.columns:
                    df[y_col] *= 100

            # Filter invalid rows (nav > 100 or empty value/qty)
            valid_mask = df.apply(
                lambda r: not ((r.iloc[6] > 100.0) or (r.iloc[4] == 0 and r.iloc[5] == 0)), 
                axis=1
            )
            df = df[valid_mask]
            
            df.to_excel(os.path.join(self.final_folder, filename), index=False)
            logger.info(f"Saved cleaned file: {filename}")

    def _join_bse_schemedata(self, portfolio_df: pd.DataFrame):
        """Enrich data with BSE ISINs and standardize Scheme Names to Title Case."""
        
        # 1. Load BSE Reference File
        try:
            df_ref = pd.read_csv(self.path_bse_schemedata, encoding='latin1', low_memory=False)
        except (UnicodeDecodeError, FileNotFoundError):
            try:
                df_ref = pd.read_csv(self.path_bse_schemedata, low_memory=False)
            except FileNotFoundError:
                logger.error("BSE Scheme file not found. Skipping enrichment.")
                return portfolio_df

        # 2. Prepare Reference Data
        # Generate standardized match key and aggregate ISINs into a unique list
        df_ref["match_key"] = df_ref["Scheme Name"].apply(self._standardize_scheme_name)
        
        ref_data = df_ref.groupby("match_key").agg({
            "ISIN": lambda x: list(sorted(set(x)))
        }).reset_index()

        # Generate official display name (Title Case) from the standardized key
        ref_data["BSE_Cleaned_Name"] = ref_data["match_key"].str.title()
        ref_data = ref_data.rename(columns={"ISIN": "bse_isin_list"})

        # 3. Merge Data
        # Join Portfolio data with BSE data using the standardized key
        merged_df = portfolio_df.merge(
            ref_data,
            how="left",
            left_on=portfolio_df["Scheme Name"].astype(str).apply(self._standardize_scheme_name),
            right_on="match_key"
        )

        # 4. Name Normalization
        # Prioritize Title-Cased BSE name; fallback to original Excel name if no match found
        merged_df["Scheme Name"] = merged_df["BSE_Cleaned_Name"].fillna(merged_df["Scheme Name"])
        
        # Remove intermediate merge columns and duplicate name columns
        cols_to_drop = ["match_key", "BSE_Cleaned_Name", "Scheme Name_y", "Scheme Name_x"]
        merged_df = merged_df.drop(columns=cols_to_drop, errors='ignore')

        # 5. Expand and Validate ISINs
        # Explode list of ISINs into separate rows
        exploded_df = merged_df.explode("bse_isin_list").rename(columns={"bse_isin_list": "Scheme ISIN"})

        # Keep only valid ISIN formats or empty values (for unmatched schemes)
        isin_pattern = r"^[A-Z]{3}[A-Z0-9]{9}$"
        mask = (
            exploded_df["Scheme ISIN"].astype(str).str.match(isin_pattern, na=False) | 
            exploded_df["Scheme ISIN"].isna()
        )
        
        return exploded_df[mask]
    
    def compile_final_output(self):
        """Merge cleaned files, categorize, enrich with BSE data, and export."""
        files = [f for f in os.listdir(self.final_folder) if "~" not in f]
        if not files:
            logger.warning("No files found to compile.")
            return

        df = pd.concat(
            [pd.read_excel(os.path.join(self.final_folder, f)) for f in files],
            ignore_index=True
        )
        logger.info(f"Compiling {len(files)} workbooks.")

        # 1. Fuzzy Category Mapping
        if "Type" in df.columns:
            mapping_keys = [str(k) for k in CATEGORY_MAPPING.keys()]
            unique_types = np.unique(df["Type"].astype(str))
            type_map = self._fuzzy_map_category(unique_types, mapping_keys)
            df["Type"] = df["Type"].map(type_map)

        # 2. Column Cleanup
        if "yield to call (ytc)" in df.columns:
            df = df.drop("yield to call (ytc)", axis=1)

        final_columns = [
            "Name of Instrument", "Instrument ISIN", "Coupon", "Industry", "Quantity",
            "Market Value", "% to Net Assets", "Yield", "Type", "Scheme Name", "AMC"
        ]
        if len(df.columns) == len(final_columns):
            df.columns = final_columns

        # 3. Enrich with BSE Data
        df = self._join_bse_schemedata(df)

        # 4. Final Data Repairs
        # Force numeric types for Quantity/MarketValue/NAV (cols 4,5,6)
        cols_to_fix = df.columns[4:7]
        df[cols_to_fix] = df[cols_to_fix].apply(pd.to_numeric, errors='coerce').fillna(0)

        # Fix negative values (e.g. Tata MF quirks)
        neg_idxs = df[(df.iloc[:, 4:7] <= 0).all(axis=1)].index.tolist()
        df.loc[neg_idxs, df.columns[4:7]] *= -1

        # 5. Debug Mismatches
        target_col = "BSE Scheme Code"
        if target_col in df.columns:
            mismatches = df[df[target_col].isna()]["Scheme Name"].unique()
            if len(mismatches) > 0:
                print("\n" + "="*60)
                print(f"⚠️  MISMATCH: {len(mismatches)} Schemes failed to match BSE data:")
                print("-" * 60)
                for name in mismatches[:10]: print(f"   • {name}")
                if len(mismatches) > 10: print(f"   ... and {len(mismatches)-10} more.")
                print("="*60 + "\n")

        # Export
        filename = f"Portfolio_extracted_{pd.Timestamp.today().strftime('%d%m%y-%H%M')}.csv"
        df.to_csv(filename, index=False)
        logger.info("Pipeline completed successfully.")
